{% set name = "deeprad" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/mimrtl/DeepRad.git

build:
  number: 0
  script: "pip install git+https://www.github.com/keras-team/keras-contrib.git"
  
requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python
    - tensorflow-gpu
    - keras
    - seaborn
    - nibabel
    - qt
    - qimage2ndarray
    - nilearn
    - pytables
    - nomkl

test:
  imports:
    - tensorflow
    - keras
    - nibabel
    - seaborn
    - qt
    - qimage2ndarray
    - nilearn
    - pytables
    - nomkl

about:
  home: https://github.com/mimrtl/DeepRad/tree/master
  license: MIMRTL-license
  summary: 'A simple tool to setup a basic deep learning environment on medical image.'
  description: This module allows users to convert nifty files to images.

extra:
  recipe-maintainers:
    # GitHub IDs for maintainers of the recipe.
    # Always check with the people listed below if they are OK becoming maintainers of the recipe. (There will be spam!)
    - Winston Chen
